version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: my_mongo
    restart: always
    ports:
      - "87001:87001"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: