version: '3.8'

services:
  web:
    build: .
    ports:
      - "8700:8700"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - db
  mongodb:
    image: mongo
    container_name: my_mongo
    restart: always
    ports:
      - "87001:87001"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: