
services:
  web:
    build: .
    ports:
      - "8700:8700"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: books_db
    ports:
      - "8705:8705"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: